In [26]:
import altair as alt
import json
import pandas as pd
import operator
import os
import re
import statsmodels.api as sm
import matplotlib.pyplot as plt

from statistics import mean

In [27]:
visus_folder_name = 'visualizations'
os.makedirs(visus_folder_name, exist_ok=True)
visus_path = os.path.join(os.getcwd(), visus_folder_name)

In [28]:
df_zero = pd.read_json('./evaluation/zero-shot/aggregate_metrics.json')
df_zero['setting'] = 'zero-shot'
df_zero

,gemma-3-gaia-pt-br-4b-it,mixtral-8x7b-instruct-v01,sabia-3.1,granite-3-3-8b-instruct,gemini-2.5-flash,gpt-4,gervasio-7b-portuguese-ptbr-decoder,llama-3-405b-instruct,deepseek-r1-0528-qwen3-8b,setting
punchlines,"{'dice_similarity': 0.48383326234057206, 'leve...","{'dice_similarity': 0.5436144598986801, 'leven...","{'dice_similarity': 0.630631817534526, 'levens...","{'dice_similarity': 0.5282609896234121, 'leven...","{'dice_similarity': 0.6778335081234601, 'leven...","{'dice_similarity': 0.7286309002872601, 'leven...","{'dice_similarity': 0.000257997936016, 'levens...","{'dice_similarity': 0.590931409026572, 'levens...","{'dice_similarity': 0.030554225060906003, 'lev...",zero-shot
comic_styles,"{'f1_score': {'fun': 0.867699642431466, 'humor...","{'f1_score': {'fun': 0.8688327316486161, 'humo...","{'f1_score': {'fun': 0.8653846153846151, 'humo...","{'f1_score': {'fun': 0.0, 'humor': 0.222222222...","{'f1_score': {'fun': 0.7873563218390801, 'humo...","{'f1_score': {'fun': 0.851511169513797, 'humor...","{'f1_score': {'fun': 0.877419354838709, 'humor...","{'f1_score': {'fun': 0.838874680306905, 'humor...","{'f1_score': {'fun': 0.867699642431466, 'humor...",zero-shot
texts_explanations,3.391579,3.364211,4.195789,3.642105,4.635789,4.282105,1.431579,3.972632,2.776842,zero-shot

In [29]:
df_few = pd.read_json('./evaluation/few-shot/aggregate_metrics.json')
df_few['setting'] = 'few-shot'
df_few

,sabia-3.1,granite-3-3-8b-instruct,gemini-2.5-flash,gpt-4,llama-3-405b-instruct,setting
punchlines,"{'dice_similarity': 0.5864655386237151, 'leven...","{'dice_similarity': 0.027473348161923, 'levens...","{'dice_similarity': 0.714440705209612, 'levens...","{'dice_similarity': 0.726885298356532, 'levens...","{'dice_similarity': 0.646843156162171, 'levens...",few-shot
comic_styles,"{'f1_score': {'fun': 0.7482014388489201, 'humo...","{'f1_score': {'fun': 0.8158567774936061, 'humo...","{'f1_score': {}, 'precision': {}, 'recall': {}...","{'f1_score': {'fun': 0.8602941176470581, 'humo...","{'f1_score': {'fun': 0.8490284005979071, 'humo...",few-shot
texts_explanations,4.090526,3.543158,4.344828,4.164211,3.696842,few-shot

In [30]:
df_all = pd.concat([df_zero, df_few])
df_all = df_all.reset_index().rename(columns={'index': 'task'})

df_long = df_all.melt(
    id_vars=['task', 'setting'], 
    var_name='model', 
    value_name='score'
)

df_long

,task,setting,model,score
0,punchlines,zero-shot,gemma-3-gaia-pt-br-4b-it,"{'dice_similarity': 0.48383326234057206, 'leve..."
1,comic_styles,zero-shot,gemma-3-gaia-pt-br-4b-it,"{'f1_score': {'fun': 0.867699642431466, 'humor..."
2,texts_explanations,zero-shot,gemma-3-gaia-pt-br-4b-it,3.391579
3,punchlines,few-shot,gemma-3-gaia-pt-br-4b-it,NaN
4,comic_styles,few-shot,gemma-3-gaia-pt-br-4b-it,NaN
5,texts_explanations,few-shot,gemma-3-gaia-pt-br-4b-it,NaN
6,punchlines,zero-shot,mixtral-8x7b-instruct-v01,"{'dice_similarity': 0.5436144598986801, 'leven..."
7,comic_styles,zero-shot,mixtral-8x7b-instruct-v01,"{'f1_score': {'fun': 0.8688327316486161, 'humo..."
8,texts_explanations,zero-shot,mixtral-8x7b-instruct-v01,3.364211
9,punchlines,few-shot,mixtral-8x7b-instruct-v01,NaN
10,comic_styles,few-shot,mixtral-8x7b-instruct-v01,NaN
11,texts_explanations,few-shot,mixtral-8x7b-instruct-v01,NaN
12,punchlines,zero-shot,sabia-3.1,"{'dice_similarity': 0.630631817534526, 'levens..."
13,comic_styles,zero-shot,sabia-3.1,"{'f1_score': {'fun': 0.8653846153846151, 'humo..."
14,texts_explanations,zero-shot,sabia-3.1,4.195789
15,punchlines,few-shot,sabia-3.1,"{'dice_similarity': 0.5864655386237151, 'leven..."
16,comic_styles,few-shot,sabia-3.1,"{'f1_score': {'fun': 0.7482014388489201, 'humo..."
17,texts_explanations,few-shot,sabia-3.1,4.090526
18,punchlines,zero-shot,granite-3-3-8b-instruct,"{'dice_similarity': 0.5282609896234121, 'leven..."
19,comic_styles,zero-shot,granite-3-3-8b-instruct,"{'f1_score': {'fun': 0.0, 'humor': 0.222222222..."
20,texts_explanations,zero-shot,granite-3-3-8b-instruct,3.642105
21,punchlines,few-shot,granite-3-3-8b-instruct,"{'dice_similarity': 0.027473348161923, 'levens..."
22,comic_styles,few-shot,granite-3-3-8b-instruct,"{'f1_score': {'fun': 0.8158567774936061, 'humo..."
23,texts_explanations,few-shot,granite-3-3-8b-instruct,3.543158
24,punchlines,zero-shot,gemini-2.5-flash,"{'dice_similarity': 0.6778335081234601, 'leven..."
25,comic_styles,zero-shot,gemini-2.5-flash,"{'f1_score': {'fun': 0.7873563218390801, 'humo..."
26,texts_explanations,zero-shot,gemini-2.5-flash,4.635789
27,punchlines,few-shot,gemini-2.5-flash,"{'dice_similarity': 0.714440705209612, 'levens..."
28,comic_styles,few-shot,gemini-2.5-flash,"{'f1_score': {}, 'precision': {}, 'recall': {}..."
29,texts_explanations,few-shot,gemini-2.5-flash,4.344828
30,punchlines,zero-shot,gpt-4,"{'dice_similarity': 0.7286309002872601, 'leven..."
31,comic_styles,zero-shot,gpt-4,"{'f1_score': {'fun': 0.851511169513797, 'humor..."
32,texts_explanations,zero-shot,gpt-4,4.282105
33,punchlines,few-shot,gpt-4,"{'dice_similarity': 0.726885298356532, 'levens..."
34,comic_styles,few-shot,gpt-4,"{'f1_score': {'fun': 0.8602941176470581, 'humo..."
35,texts_explanations,few-shot,gpt-4,4.164211
36,punchlines,zero-shot,gervasio-7b-portuguese-ptbr-decoder,"{'dice_similarity': 0.000257997936016, 'levens..."
37,comic_styles,zero-shot,gervasio-7b-portuguese-ptbr-decoder,"{'f1_score': {'fun': 0.877419354838709, 'humor..."
38,texts_explanations,zero-shot,gervasio-7b-portuguese-ptbr-decoder,1.431579
39,punchlines,few-shot,gervasio-7b-portuguese-ptbr-decoder,NaN
40,comic_styles,few-shot,gervasio-7b-portuguese-ptbr-decoder,NaN
41,texts_explanations,few-shot,gervasio-7b-portuguese-ptbr-decoder,NaN
42,punchlines,zero-shot,llama-3-405b-instruct,"{'dice_similarity': 0.590931409026572, 'levens..."
43,comic_styles,zero-shot,llama-3-405b-instruct,"{'f1_score': {'fun': 0.838874680306905, 'humor..."
44,texts_explanations,zero-shot,llama-3-405b-instruct,3.972632
45,punchlines,few-shot,llama-3-405b-instruct,"{'dice_similarity': 0.646843156162171, 'levens..."
46,comic_styles,few-shot,llama-3-405b-instruct,"{'f1_score': {'fun': 0.8490284005979071, 'humo..."
47,texts_explanations,few-shot,llama-3-405b-instruct,3.696842
48,punchlines,zero-shot,deepseek-r1-0528-qwen3-8b,"{'dice_similarity': 0.030554225060906003, 'lev..."
49,comic_styles,zero-shot,deepseek-r1-0528-qwen3-8b,"{'f1_score': {'fun': 0.867699642431466, 'humor..."
50,texts_explanations,zero-shot,deepseek-r1-0528-qwen3-8b,2.776842
51,punchlines,few-shot,deepseek-r1-0528-qwen3-8b,NaN
52,comic_styles,few-shot,deepseek-r1-0528-qwen3-8b,NaN
53,texts_explanations,few-shot,deepseek-r1-0528-qwen3-8b,NaN

In [31]:
model_short_names = {
    'gemma-3-gaia-pt-br-4b-it': 'Gemma 3 Gaia (4B)',
    'mixtral-8x7b-instruct-v01': 'Mixtral v01 (8×7B)',
    'sabia-3.1': 'Sabia 3.1',
    'granite-3-3-8b-instruct': 'Granite 3.3 (8B)',
    'gemini-2.5-flash': 'Gemini 2.5 Flash',
    'gpt-4': 'GPT-4',
    'llama-3-405b-instruct': 'LLaMA 3 (405B)',
    'deepseek-r1-0528-qwen3-8b': 'DeepSeek R1 (8B)',
    'gervasio-7b-portuguese-ptbr-decoder': 'Gervasio (7B)'
}

df_long['model'] = df_long['model'].apply(lambda model_name: model_short_names[model_name])
df_long

,task,setting,model,score
0,punchlines,zero-shot,Gemma 3 Gaia (4B),"{'dice_similarity': 0.48383326234057206, 'leve..."
1,comic_styles,zero-shot,Gemma 3 Gaia (4B),"{'f1_score': {'fun': 0.867699642431466, 'humor..."
2,texts_explanations,zero-shot,Gemma 3 Gaia (4B),3.391579
3,punchlines,few-shot,Gemma 3 Gaia (4B),NaN
4,comic_styles,few-shot,Gemma 3 Gaia (4B),NaN
5,texts_explanations,few-shot,Gemma 3 Gaia (4B),NaN
6,punchlines,zero-shot,Mixtral v01 (8×7B),"{'dice_similarity': 0.5436144598986801, 'leven..."
7,comic_styles,zero-shot,Mixtral v01 (8×7B),"{'f1_score': {'fun': 0.8688327316486161, 'humo..."
8,texts_explanations,zero-shot,Mixtral v01 (8×7B),3.364211
9,punchlines,few-shot,Mixtral v01 (8×7B),NaN
10,comic_styles,few-shot,Mixtral v01 (8×7B),NaN
11,texts_explanations,few-shot,Mixtral v01 (8×7B),NaN
12,punchlines,zero-shot,Sabia 3.1,"{'dice_similarity': 0.630631817534526, 'levens..."
13,comic_styles,zero-shot,Sabia 3.1,"{'f1_score': {'fun': 0.8653846153846151, 'humo..."
14,texts_explanations,zero-shot,Sabia 3.1,4.195789
15,punchlines,few-shot,Sabia 3.1,"{'dice_similarity': 0.5864655386237151, 'leven..."
16,comic_styles,few-shot,Sabia 3.1,"{'f1_score': {'fun': 0.7482014388489201, 'humo..."
17,texts_explanations,few-shot,Sabia 3.1,4.090526
18,punchlines,zero-shot,Granite 3.3 (8B),"{'dice_similarity': 0.5282609896234121, 'leven..."
19,comic_styles,zero-shot,Granite 3.3 (8B),"{'f1_score': {'fun': 0.0, 'humor': 0.222222222..."
20,texts_explanations,zero-shot,Granite 3.3 (8B),3.642105
21,punchlines,few-shot,Granite 3.3 (8B),"{'dice_similarity': 0.027473348161923, 'levens..."
22,comic_styles,few-shot,Granite 3.3 (8B),"{'f1_score': {'fun': 0.8158567774936061, 'humo..."
23,texts_explanations,few-shot,Granite 3.3 (8B),3.543158
24,punchlines,zero-shot,Gemini 2.5 Flash,"{'dice_similarity': 0.6778335081234601, 'leven..."
25,comic_styles,zero-shot,Gemini 2.5 Flash,"{'f1_score': {'fun': 0.7873563218390801, 'humo..."
26,texts_explanations,zero-shot,Gemini 2.5 Flash,4.635789
27,punchlines,few-shot,Gemini 2.5 Flash,"{'dice_similarity': 0.714440705209612, 'levens..."
28,comic_styles,few-shot,Gemini 2.5 Flash,"{'f1_score': {}, 'precision': {}, 'recall': {}..."
29,texts_explanations,few-shot,Gemini 2.5 Flash,4.344828
30,punchlines,zero-shot,GPT-4,"{'dice_similarity': 0.7286309002872601, 'leven..."
31,comic_styles,zero-shot,GPT-4,"{'f1_score': {'fun': 0.851511169513797, 'humor..."
32,texts_explanations,zero-shot,GPT-4,4.282105
33,punchlines,few-shot,GPT-4,"{'dice_similarity': 0.726885298356532, 'levens..."
34,comic_styles,few-shot,GPT-4,"{'f1_score': {'fun': 0.8602941176470581, 'humo..."
35,texts_explanations,few-shot,GPT-4,4.164211
36,punchlines,zero-shot,Gervasio (7B),"{'dice_similarity': 0.000257997936016, 'levens..."
37,comic_styles,zero-shot,Gervasio (7B),"{'f1_score': {'fun': 0.877419354838709, 'humor..."
38,texts_explanations,zero-shot,Gervasio (7B),1.431579
39,punchlines,few-shot,Gervasio (7B),NaN
40,comic_styles,few-shot,Gervasio (7B),NaN
41,texts_explanations,few-shot,Gervasio (7B),NaN
42,punchlines,zero-shot,LLaMA 3 (405B),"{'dice_similarity': 0.590931409026572, 'levens..."
43,comic_styles,zero-shot,LLaMA 3 (405B),"{'f1_score': {'fun': 0.838874680306905, 'humor..."
44,texts_explanations,zero-shot,LLaMA 3 (405B),3.972632
45,punchlines,few-shot,LLaMA 3 (405B),"{'dice_similarity': 0.646843156162171, 'levens..."
46,comic_styles,few-shot,LLaMA 3 (405B),"{'f1_score': {'fun': 0.8490284005979071, 'humo..."
47,texts_explanations,few-shot,LLaMA 3 (405B),3.696842
48,punchlines,zero-shot,DeepSeek R1 (8B),"{'dice_similarity': 0.030554225060906003, 'lev..."
49,comic_styles,zero-shot,DeepSeek R1 (8B),"{'f1_score': {'fun': 0.867699642431466, 'humor..."
50,texts_explanations,zero-shot,DeepSeek R1 (8B),2.776842
51,punchlines,few-shot,DeepSeek R1 (8B),NaN
52,comic_styles,few-shot,DeepSeek R1 (8B),NaN
53,texts_explanations,few-shot,DeepSeek R1 (8B),NaN

In [32]:
# 1. Filtrar só punchlines
df_punch = df_long.query("task == 'punchlines'").copy()
df_punch.head()

,task,setting,model,score
0,punchlines,zero-shot,Gemma 3 Gaia (4B),"{'dice_similarity': 0.48383326234057206, 'leve..."
3,punchlines,few-shot,Gemma 3 Gaia (4B),NaN
6,punchlines,zero-shot,Mixtral v01 (8×7B),"{'dice_similarity': 0.5436144598986801, 'leven..."
9,punchlines,few-shot,Mixtral v01 (8×7B),NaN
12,punchlines,zero-shot,Sabia 3.1,"{'dice_similarity': 0.630631817534526, 'levens..."

In [33]:
valid_models = [
    model for model in df_punch['model'].unique()
    if all(
        isinstance(v, dict) and v.get('dice_similarity') is not None
        for v in df_punch.loc[df_punch['model'] == model, 'score']
    )
]

df_punch_plot = df_punch[df_punch['model'].isin(valid_models)]

In [34]:
import altair as alt
import os

df_plot = df_punch_plot.copy()
df_plot['dice_similarity'] = df_plot['score'].apply(lambda x: x['dice_similarity'] if isinstance(x, dict) else None)
dice_order = df_plot[df_plot['setting'] == 'zero-shot'].sort_values('dice_similarity', ascending=False)['model'].tolist()
df_plot['setting'] = pd.Categorical(df_plot['setting'], categories=['zero-shot', 'few-shot'], ordered=True)

chart_dice = alt.Chart(df_plot).mark_bar(size=20).encode(
    y=alt.Y('model:N', sort=dice_order, title=' ', axis=alt.Axis(grid=False)),
    x=alt.X('dice_similarity:Q', title='Média da Similaridade de Dice', axis=alt.Axis(grid=False, titleY=30)),
    color=alt.Color('setting:N', title='Configuração'),
    yOffset=alt.YOffset('setting:N')
).properties(
    width=500,
    height=400,
    title='Comparação Zero-shot vs Few-shot — Identificação de Punchlines'
)

visus_path = visus_folder_name
os.makedirs(visus_path, exist_ok=True)
chart_dice.save(os.path.join(visus_path, "similaridade_dice_vertical_barras.png"), scale_factor=3.0)
chart_dice.show()

alt.Chart(...)

In [35]:
df_texts = df_long.query("task == 'texts_explanations'").copy()

valid_models = [
    model for model in df_texts['model'].unique()
    if all(
        pd.notna(v)
        for v in df_texts.loc[df_texts['model'] == model, 'score']
    )
]

df_texts_plot = df_texts[df_texts['model'].isin(valid_models)]
df_texts_plot

                  task    setting             model     score
14  texts_explanations  zero-shot         Sabia 3.1  4.195789
17  texts_explanations   few-shot         Sabia 3.1  4.090526
20  texts_explanations  zero-shot  Granite 3.3 (8B)  3.642105
23  texts_explanations   few-shot  Granite 3.3 (8B)  3.543158
26  texts_explanations  zero-shot  Gemini 2.5 Flash  4.635789
29  texts_explanations   few-shot  Gemini 2.5 Flash  4.344828
32  texts_explanations  zero-shot             GPT-4  4.282105
35  texts_explanations   few-shot             GPT-4  4.164211
44  texts_explanations  zero-shot    LLaMA 3 (405B)  3.972632
47  texts_explanations   few-shot    LLaMA 3 (405B)  3.696842

In [36]:
df_plot = df_texts_plot.copy()
df_plot['metric'] = df_plot['score']
zero_shot_order = df_plot[df_plot['setting'] == 'zero-shot'].sort_values('metric', ascending=False)['model'].tolist()
df_plot['setting'] = pd.Categorical(df_plot['setting'], categories=['zero-shot', 'few-shot'], ordered=True)

chart_texts = alt.Chart(df_plot).mark_bar(size=20).encode(
    y=alt.Y('model:N', sort=zero_shot_order, title=' ', axis=alt.Axis(grid=False)),
    x=alt.X(
        'metric:Q',
        title='Média do Nível de Concordância - Modelo Juiz',
        axis=alt.Axis(grid=False, titleY=30),
        scale=alt.Scale(domain=[1, 5], clamp = True) 
    ),
    color=alt.Color('setting:N', title='Configuração'),
    yOffset=alt.YOffset('setting:N')
).properties(
    width=500,
    height=400,
    title='Comparação Zero-shot vs Few-shot — Explicações dos Textos'
)

visus_path = visus_folder_name
os.makedirs(visus_path, exist_ok=True)
chart_texts.save(os.path.join(visus_path, "texts_explanations_vertical_barras.png"), scale_factor=3.0)
chart_texts.show()

alt.Chart(...)

In [37]:
df_comic = df_long.query("task == 'comic_styles'").copy()
df_comic

,task,setting,model,score
1,comic_styles,zero-shot,Gemma 3 Gaia (4B),"{'f1_score': {'fun': 0.867699642431466, 'humor..."
4,comic_styles,few-shot,Gemma 3 Gaia (4B),NaN
7,comic_styles,zero-shot,Mixtral v01 (8×7B),"{'f1_score': {'fun': 0.8688327316486161, 'humo..."
10,comic_styles,few-shot,Mixtral v01 (8×7B),NaN
13,comic_styles,zero-shot,Sabia 3.1,"{'f1_score': {'fun': 0.8653846153846151, 'humo..."
16,comic_styles,few-shot,Sabia 3.1,"{'f1_score': {'fun': 0.7482014388489201, 'humo..."
19,comic_styles,zero-shot,Granite 3.3 (8B),"{'f1_score': {'fun': 0.0, 'humor': 0.222222222..."
22,comic_styles,few-shot,Granite 3.3 (8B),"{'f1_score': {'fun': 0.8158567774936061, 'humo..."
25,comic_styles,zero-shot,Gemini 2.5 Flash,"{'f1_score': {'fun': 0.7873563218390801, 'humo..."
28,comic_styles,few-shot,Gemini 2.5 Flash,"{'f1_score': {}, 'precision': {}, 'recall': {}..."
31,comic_styles,zero-shot,GPT-4,"{'f1_score': {'fun': 0.851511169513797, 'humor..."
34,comic_styles,few-shot,GPT-4,"{'f1_score': {'fun': 0.8602941176470581, 'humo..."
37,comic_styles,zero-shot,Gervasio (7B),"{'f1_score': {'fun': 0.877419354838709, 'humor..."
40,comic_styles,few-shot,Gervasio (7B),NaN
43,comic_styles,zero-shot,LLaMA 3 (405B),"{'f1_score': {'fun': 0.838874680306905, 'humor..."
46,comic_styles,few-shot,LLaMA 3 (405B),"{'f1_score': {'fun': 0.8490284005979071, 'humo..."
49,comic_styles,zero-shot,DeepSeek R1 (8B),"{'f1_score': {'fun': 0.867699642431466, 'humor..."
52,comic_styles,few-shot,DeepSeek R1 (8B),NaN

In [38]:
valid_models = [
    model for model in df_comic['model'].unique()
    if all(
        isinstance(v, dict) and 'f1_score' in v and all(pd.notna(score) for score in v['f1_score'].values())
        for v in df_comic.loc[df_comic['model'] == model, 'score']
    ) and model != 'Gemini 2.5 Flash'
]


df_comic_plot = df_comic[df_comic['model'].isin(valid_models)].copy()

# Expandir os dicionários f1_score em linhas longas
rows = []
for _, row in df_comic_plot.iterrows():
    f1_scores = row['score']['f1_score']
    for style, value in f1_scores.items():
        if pd.notna(value):
            rows.append({
                'model': row['model'],
                'setting': row['setting'],
                'style': style,
                'score': value
            })

df_comic_long = pd.DataFrame(rows)

# Ordenar modelos pelo zero-shot (média de todos os estilos)
model_order = (
    df_comic_long[df_comic_long['setting'] == 'zero-shot']
    .groupby('model')['score'].mean()
    .sort_values(ascending=False)
    .index.tolist()
)

# Transformar setting em categoria ordenada
df_comic_long['setting'] = pd.Categorical(df_comic_long['setting'], categories=['zero-shot', 'few-shot'], ordered=True)

# Gráfico horizontal: barras por estilo, zero-shot acima do few-shot
chart_comic = alt.Chart(df_comic_long).mark_bar(size=20).encode(
    y=alt.Y('model:N', sort=model_order, title=' ', axis=alt.Axis(grid=False)),
    x=alt.X('score:Q', title='F1 Score', axis=alt.Axis(grid=False, titleY=30), scale=alt.Scale(domain=[0,1], clamp=True)),
    color=alt.Color('setting:N', title='Configuração'),
    yOffset=alt.YOffset('setting:N'),
    column=alt.Column('style:N', title=' ')  # cada estilo em uma coluna
).properties(
    width=150,
    height=400,
    title='Comparação Zero-shot vs Few-shot — Estilos Cômicos (F1 Score)'
)

# Salvar e mostrar
visus_path = visus_folder_name
os.makedirs(visus_path, exist_ok=True)
chart_comic.save(os.path.join(visus_path, "comic_styles_vertical_barras.png"), scale_factor=3.0)
chart_comic.show()

alt.Chart(...)

In [39]:
def graph_all_models_per_style(model_names):
    data = []

    for model_name in model_names:
        f1_scores = df_comic_styles.loc[model_name]['f1_score']
        for style, score in f1_scores.items():
            data.append({
                'style': style,
                'model': model_name,
                'score': score
            })

    df_all = pd.DataFrame(data)

    chart = alt.Chart(df_all).mark_bar().encode(
        x=alt.X('style:N', title=None, axis=alt.Axis(labelAngle=0)),
        y=alt.Y('score:Q', title='F1-Score'),
        color=alt.Color('model:N', title='Modelo'),
        xOffset=alt.X('model:N')  # <-- barras lado a lado dentro do mesmo estilo
    ).properties(
        width=500,
        height=400,
        title='F1-Score por Estilo Cômico e Modelo'
    )

    chart.save(os.path.join(visus_path, "f1_per_style_all_models.png"), scale_factor=3.0)
    chart.show()

model_names = df_comic_styles.index
graph_all_models_per_style(model_names)

NameError: name 'df_comic_styles' is not defined