In [122]:
import altair as alt
import json
import pandas as pd
import operator
import os

In [123]:
visus_folder_name = 'visualizations'
os.makedirs(visus_folder_name, exist_ok=True)
visus_path = os.path.join(os.getcwd(), visus_folder_name)

In [124]:
df = pd.read_json('./evaluation/aggregate_metrics.json')
df

,gemma-3-gaia-pt-br-4b-it,mixtral-8x7b-instruct-v01,sabia-3.1,granite-3-3-8b-instruct,gemini-2.5-flash,gpt-4,llama-3-405b-instruct,deepseek-r1-0528-qwen3-8b
punchlines,"{'dice_similarity': 0.48383326234057206, 'leve...","{'dice_similarity': 0.5436144598986801, 'leven...","{'dice_similarity': 0.630631817534526, 'levens...","{'dice_similarity': 0.5282609896234121, 'leven...","{'dice_similarity': 0.6778335081234601, 'leven...","{'dice_similarity': 0.7286309002872601, 'leven...","{'dice_similarity': 0.590931409026572, 'levens...","{'dice_similarity': 0.030554225060906003, 'lev..."
comic_styles,"{'f1_score': {'fun': 0.867699642431466, 'humor...","{'f1_score': {'fun': 0.8688327316486161, 'humo...","{'f1_score': {'fun': 0.8653846153846151, 'humo...","{'f1_score': {'fun': 0.0, 'humor': 0.222222222...","{'f1_score': {'fun': 0.7873563218390801, 'humo...","{'f1_score': {'fun': 0.851511169513797, 'humor...","{'f1_score': {'fun': 0.838874680306905, 'humor...","{'f1_score': {'fun': 0.8586762075134161, 'humo..."
texts_explanations,3.391579,3.364211,4.195789,3.642105,4.635789,4.282105,3.972632,2.776842

In [125]:
apelidos = {
    'gemma-3-gaia-pt-br-4b-it': 'Gemma 3 Gaia (4B)',
    'mixtral-8x7b-instruct-v01': 'Mixtral v01 (8×7B)',
    'sabia-3.1': 'Sabia 3.1',
    'granite-3-3-8b-instruct': 'Granite 3.3 (8B)',
    'gemini-2.5-flash': 'Gemini 2.5 Flash',
    'gpt-4': 'GPT-4',
    'llama-3-405b-instruct': 'LLaMA 3 (405B)',
    'deepseek-r1-0528-qwen3-8b': 'DeepSeek R1 (8B)'
}

df = df.rename(columns=apelidos)

In [126]:
df_punchlines = pd.DataFrame(df.loc["punchlines"].tolist(), index=df.columns)
df_punchlines

,dice_similarity,levenshtein_distance,hit_rate_pre_treatment,hit_rate
Gemma 3 Gaia (4B),0.483833,28.490526,0.000000,0.993684
Mixtral v01 (8×7B),0.543614,25.267368,0.989474,0.989474
Sabia 3.1,0.630632,23.330526,0.985263,0.995789
Granite 3.3 (8B),0.528261,31.288421,0.842105,0.945263
Gemini 2.5 Flash,0.677834,19.029474,0.993684,0.993684
GPT-4,0.728631,24.040000,0.997895,0.997895
LLaMA 3 (405B),0.590931,24.128421,0.983158,0.993684
DeepSeek R1 (8B),0.030554,34.528421,0.000000,0.157895

In [127]:
df_dice = df_punchlines[['dice_similarity']].reset_index().rename(columns={'index': 'model'})
df_lev = df_punchlines[['levenshtein_distance']].reset_index().rename(columns={'index': 'model'})

dice_order = df_dice.sort_values('dice_similarity')['model'].tolist()[::-1]
lev_order = df_lev.sort_values('levenshtein_distance')['model'].tolist()[::1]

chart_dice = alt.layer(
    alt.Chart(df_dice).mark_bar(size=80).encode(
        x=alt.X('model:N', sort=dice_order, title=' ',
                scale=alt.Scale(paddingInner=0.1), axis=alt.Axis(grid=False)),
        y=alt.Y('dice_similarity:Q', title='Média da Similaridade de Dice', axis=alt.Axis(grid=False)),
        color=alt.Color('model:N', legend=None)
    ),
    alt.Chart(df_dice).mark_text(
        align='center',
        baseline='bottom',
        dy=-2
    ).encode(
        x=alt.X('model:N', sort=dice_order),
        y='dice_similarity:Q',
        text=alt.Text('dice_similarity:Q', format=".2f")
    )
).properties(
    width=850,
    height=300,
    title='Sobreposição de Punchlines por Modelo (Similaridade de Dice)'
).configure_axisX(
    labelAngle=0,
    labelAlign='center'
)

chart_dice.save(os.path.join(visus_path, "similaridade_dice.png"), scale_factor=3.0)
chart_dice.show()

alt.LayerChart(...)

In [128]:
'''chart_lev = alt.layer(
    alt.Chart(df_lev).mark_bar(size=80).encode(
        x=alt.X('model:N', sort=lev_order, title=' ',
                scale=alt.Scale(paddingInner=0.1),
                axis=alt.Axis(grid=False)),
        y=alt.Y('levenshtein_distance:Q', title='Média da Distância de Levenshtein',
                scale = alt.Scale(paddingInner=1, domain=[0, 36], nice = False),
                axis=alt.Axis(grid=False), 
                ),
        color=alt.Color('model:N', legend=None)
    ),
    alt.Chart(df_lev).mark_text(
        align='center',
        baseline='bottom',
        dy=-2
    ).encode(
        x=alt.X('model:N', sort=lev_order),
        y='levenshtein_distance:Q',
        text=alt.Text('levenshtein_distance:Q', format=".2f")
    )
).properties(
    width=1100,
    height=600,
    title='Distância de Punchlines por Modelo (Distância de Levenshtein)'
).configure_axisX(
    labelAngle=0,
    labelAlign='center'
)

chart_dice.save(os.path.join(visus_path,"punchlines_dice.png"), scale_factor=3.0)
chart_lev.save(os.path.join(visus_path, "punchlines_levenshtein.png"), scale_factor=3.0)

chart_lev.show()'''

'chart_lev = alt.layer(\n    alt.Chart(df_lev).mark_bar(size=80).encode(\n        x=alt.X(\'model:N\', sort=lev_order, title=\' \',\n                scale=alt.Scale(paddingInner=0.1),\n                axis=alt.Axis(grid=False)),\n        y=alt.Y(\'levenshtein_distance:Q\', title=\'Média da Distância de Levenshtein\',\n                scale = alt.Scale(paddingInner=1, domain=[0, 36], nice = False),\n                axis=alt.Axis(grid=False), \n                ),\n        color=alt.Color(\'model:N\', legend=None)\n    ),\n    alt.Chart(df_lev).mark_text(\n        align=\'center\',\n        baseline=\'bottom\',\n        dy=-2\n    ).encode(\n        x=alt.X(\'model:N\', sort=lev_order),\n        y=\'levenshtein_distance:Q\',\n        text=alt.Text(\'levenshtein_distance:Q\', format=".2f")\n    )\n).properties(\n    width=1100,\n    height=600,\n    title=\'Distância de Punchlines por Modelo (Distância de Levenshtein)\'\n).configure_axisX(\n    labelAngle=0,\n    labelAlign=\'center\'\n)\n\nchart_dice.save(os.path.join(visus_path,"punchlines_dice.png"), scale_factor=3.0)\nchart_lev.save(os.path.join(visus_path, "punchlines_levenshtein.png"), scale_factor=3.0)\n\nchart_lev.show()'

In [129]:
df_texts_explanations = df.loc["texts_explanations"].to_frame().T
df_texts_explanations

,Gemma 3 Gaia (4B),Mixtral v01 (8×7B),Sabia 3.1,Granite 3.3 (8B),Gemini 2.5 Flash,GPT-4,LLaMA 3 (405B),DeepSeek R1 (8B)
texts_explanations,3.391579,3.364211,4.195789,3.642105,4.635789,4.282105,3.972632,2.776842

In [130]:
texts_expl = df.loc["texts_explanations"].astype(float)
texts_df = texts_expl.reset_index()
texts_df.columns = ["Modelo", "Concordância Média"]

max_val = texts_df["Concordância Média"].max()

chart = alt.layer(
    alt.Chart(texts_df).mark_bar(size=80).encode(
        y=alt.Y('Concordância Média:Q',
                title='Nível médio de concordância (Modelo Juiz)',
                scale=alt.Scale(domain=[1, max_val * 1.05], clamp=True),  # começa em 1 e folga no topo
                axis=alt.Axis(grid=False)),
        x=alt.X('Modelo:N',
                sort='-y',
                title='',
                axis=alt.Axis(grid=False, labelAngle=0)),
        color=alt.Color('Modelo:N', legend=None),
        tooltip=["Modelo", "Concordância Média"]
    ),
    alt.Chart(texts_df).mark_text(
        align='center',
        baseline='bottom',
        dy=-3
    ).encode(
        x=alt.X('Modelo:N', sort='-y'),
        y='Concordância Média:Q',
        text=alt.Text('Concordância Média:Q', format='.2f')
    )
).properties(
    width=850,
    height=400,
    title="Avaliação das Explicações dos Textos Humorísticos por Modelo"
)

chart.save(os.path.join(visus_path, "explicacoes_concordancia.png"), scale_factor=3.0)
chart

alt.LayerChart(...)

In [131]:
df_comic_styles = pd.DataFrame(df.loc["comic_styles"].dropna().tolist(), index=df.columns[df.loc["comic_styles"].notna()])
df_comic_styles

,f1_score,precision,recall,accuracy,f1_macro,f1_micro,hit_rate_pre_treatment,hit_rate,omission_rate
Gemma 3 Gaia (4B),"{'fun': 0.867699642431466, 'humor': 0.84987893...","{'fun': 0.7663157894736841, 'humor': 0.7389473...","{'fun': 1.0, 'humor': 1.0, 'nonsense': 1.0, 'w...","{'fun': 0.7663157894736841, 'humor': 0.7389473...",0.125000,0.667135,0.0,1.000000,0.000000
Mixtral v01 (8×7B),"{'fun': 0.8688327316486161, 'humor': 0.8511685...","{'fun': 0.7680851063829781, 'humor': 0.7408993...","{'fun': 1.0, 'humor': 1.0, 'nonsense': 1.0, 'w...","{'fun': 0.7680851063829781, 'humor': 0.7408993...",0.139617,0.692837,0.0,0.982895,0.017105
Sabia 3.1,"{'fun': 0.8653846153846151, 'humor': 0.8462515...","{'fun': 0.769230769230769, 'humor': 0.76376146...","{'fun': 0.989010989010989, 'humor': 0.94871794...","{'fun': 0.764210526315789, 'humor': 0.74526315...",0.199594,0.832207,0.0,1.000000,0.000000
Granite 3.3 (8B),"{'fun': 0.0, 'humor': 0.22222222222222202, 'no...","{'fun': 0.0, 'humor': 0.833333333333333, 'nons...","{'fun': 0.0, 'humor': 0.128205128205128, 'nons...","{'fun': 0.23368421052631502, 'humor': 0.336842...",0.184258,0.791349,0.0,1.000000,0.000000
Gemini 2.5 Flash,"{'fun': 0.7873563218390801, 'humor': 0.5658914...","{'fun': 0.825301204819277, 'humor': 0.88484848...","{'fun': 0.7527472527472521, 'humor': 0.4159544...","{'fun': 0.688421052631578, 'humor': 0.52842105...",0.249473,0.997890,1.0,1.000000,0.000000
GPT-4,"{'fun': 0.851511169513797, 'humor': 0.55619047...","{'fun': 0.816120906801007, 'humor': 0.83908045...","{'fun': 0.8901098901098901, 'humor': 0.4159544...","{'fun': 0.7621052631578941, 'humor': 0.5094736...",0.248408,0.993644,1.0,1.000000,0.000000
LLaMA 3 (405B),"{'fun': 0.838874680306905, 'humor': 0.73851030...","{'fun': 0.7846889952153111, 'humor': 0.8321428...","{'fun': 0.9010989010989011, 'humor': 0.6638176...","{'fun': 0.734736842105263, 'humor': 0.65263157...",0.242541,0.970748,0.0,1.000000,0.000000
DeepSeek R1 (8B),"{'fun': 0.8586762075134161, 'humor': 0.8421052...","{'fun': 0.7523510971786831, 'humor': 0.7272727...","{'fun': 1.0, 'humor': 1.0, 'nonsense': 1.0, 'w...","{'fun': 0.7523510971786831, 'humor': 0.7272727...",0.125000,0.667364,0.0,1.000000,0.000000

In [132]:
def graph_all_models_per_style(model_names):
    data = []

    for model_name in model_names:
        f1_scores = df_comic_styles.loc[model_name]['f1_score']
        for style, score in f1_scores.items():
            data.append({
                'style': style,
                'model': model_name,
                'score': score
            })

    df_all = pd.DataFrame(data)

    chart = alt.Chart(df_all).mark_bar().encode(
        x=alt.X('style:N', title=None, axis=alt.Axis(labelAngle=0)),
        y=alt.Y('score:Q', title='F1-Score'),
        color=alt.Color('model:N', title='Modelo'),
        xOffset=alt.X('model:N')  # <-- barras lado a lado dentro do mesmo estilo
    ).properties(
        width=500,
        height=400,
        title='F1-Score por Estilo Cômico e Modelo'
    )

    chart.save(os.path.join(visus_path, "f1_per_style_all_models.png"), scale_factor=3.0)
    chart.show()

model_names = df_comic_styles.index
graph_all_models_per_style(model_names)

alt.Chart(...)

In [133]:
'''
# Agrupar casos individuais em comum em que os modelos ERRARAM

# Para as punchlines:
    # Para cada modelo, pegar linhas em que dice_similarity <= 0.4

# Para os estilos cômicos:
    # Para cada modelo, em estilo cômico, pegar linhas em que erraram

# Para os punchlines
    # Para cada modelo, pegar resultados <= 2
    
# Agrupar casos individuais em comum em que os modelos ACERTARAM'''

'\n# Agrupar casos individuais em comum em que os modelos ERRARAM\n\n# Para as punchlines:\n    # Para cada modelo, pegar linhas em que dice_similarity <= 0.4\n\n# Para os estilos cômicos:\n    # Para cada modelo, em estilo cômico, pegar linhas em que erraram\n\n# Para os punchlines\n    # Para cada modelo, pegar resultados <= 2\n\n# Agrupar casos individuais em comum em que os modelos ACERTARAM'

### Análise qualitativa 1 - Erros em comum

#### 1.1 Punchlines

In [134]:
json_path = './evaluation/individual_metrics.json'
with open(json_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

rows = []
for model_key, content in data.items():
    for punchline in content.get("punchlines", []):
        row = {"source_model_key": model_key}
        row.update(punchline)
        rows.append(row)

punchlines_results_df = pd.DataFrame(rows)
required_cols = {"dice_similarity", "humorous_text", "model_name"}
missing = required_cols - set(punchlines_results_df.columns)
if missing:
    raise ValueError(f"Missing expected columns in data: {missing}")

def get_repeated_texts(df, dice_threshold, comparison_op, min_repeats=4):
    df_filtered = df[comparison_op(df["dice_similarity"], dice_threshold)].copy()
    df_filtered["humorous_text"] = df_filtered["humorous_text"].astype(str).str.strip()

    counts_per_model = (
        df_filtered
        .groupby(["humorous_text", "model_name"])
        .size()
        .unstack(fill_value=0)
    )

    counts_per_model["total_occurrences"] = counts_per_model.sum(axis=1)
    repeated_mask = counts_per_model["total_occurrences"] >= min_repeats
    repeated_texts_counts = counts_per_model[repeated_mask].sort_values("total_occurrences", ascending=False)

    model_cols = [c for c in repeated_texts_counts.columns if c != "total_occurrences"]
    repeated_texts_df = repeated_texts_counts.reset_index()
    repeated_texts_df["models"] = repeated_texts_df[model_cols].apply(
        lambda row: [m for m in model_cols if row[m] > 0],
        axis=1
    )
    return repeated_texts_df[["humorous_text", "total_occurrences", "models"]].reset_index(drop=True)

punchlines_worse_results_df = get_repeated_texts(punchlines_results_df, 0.4, operator.le, min_repeats=4)
punchlines_better_results_df = get_repeated_texts(punchlines_results_df, 0.6, operator.ge, min_repeats=4)

In [135]:
punchlines_better_results_df.head(2)

model_name,humorous_text,total_occurrences,models
0,"Porque o sofista recifense é o porra, é o mais...",8,"[deepseek-r1-0528-qwen3-8b, gemini-2.5-flash, ..."
1,"A gente viu agora, nem tem muito tempo assim, ...",7,"[gemini-2.5-flash, gemma-3-gaia-pt-br-4b-it, g..."

In [136]:
punchlines_worse_results_df.head(2)

model_name,humorous_text,total_occurrences,models
0,"E assim, eu achei muito humildade desse grande...",8,"[deepseek-r1-0528-qwen3-8b, gemini-2.5-flash, ..."
1,"Gente, aqui entrando no quarto de hotel, olha ...",8,"[deepseek-r1-0528-qwen3-8b, gemini-2.5-flash, ..."

#### 1.2 Estilos cômicos

In [137]:
json_path = './evaluation/individual_metrics.json'
with open(json_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

rows = []
for model_key, content in data.items():
    for style_metric in content.get("comic_styles", []): 
        row = {"source_model_key": model_key}
        row.update(style_metric)
        rows.append(row)

comic_styles_df = pd.DataFrame(rows)

required_cols = {"model_name", "is_correct", "comic_style", "humorous_text"}
missing = required_cols - set(comic_styles_df.columns)
if missing:
    raise ValueError(f"Missing expected columns in data: {missing}")

comic_styles_df["humorous_text"] = comic_styles_df["humorous_text"].astype(str).str.strip()

def get_common_texts_by_style(df, correct_flag, min_models=5):
    filtered = df[df["is_correct"] == correct_flag].copy()
    grouped_results = []

    for style, style_df in filtered.groupby("comic_style"):
        counts_per_model = (
            style_df.groupby(["humorous_text", "model_name"])
            .size()
            .unstack(fill_value=0)
        )
        counts_per_model["num_models"] = (counts_per_model > 0).sum(axis=1)
        mask = counts_per_model["num_models"] >= min_models
        common_texts = counts_per_model[mask].sort_values("num_models", ascending=False)

        if not common_texts.empty:
            temp_df = common_texts.reset_index()
            temp_df["comic_style"] = style
            model_cols = [c for c in temp_df.columns if c not in {"humorous_text", "comic_style", "num_models"}]
            temp_df["models"] = temp_df[model_cols].apply(
                lambda row: [m for m in model_cols if row[m] > 0],
                axis=1
            )
            grouped_results.append(temp_df[["comic_style", "humorous_text", "num_models", "models"]])

    if grouped_results:
        return pd.concat(grouped_results, ignore_index=True)
    else:
        return pd.DataFrame(columns=["comic_style", "humorous_text", "num_models", "models"])

common_errors_df = get_common_texts_by_style(comic_styles_df, correct_flag=0, min_models=4)
common_correct_df = get_common_texts_by_style(comic_styles_df, correct_flag=1, min_models=4)

In [138]:
common_correct_df

model_name,comic_style,humorous_text,num_models,models
0,cynicism,A maior concentração de tabacudo do mundo tá d...,7,"[deepseek-r1-0528-qwen3-8b, gemini-2.5-flash, ..."
1,cynicism,E o governo só faz errar nas campanhas de drog...,7,"[deepseek-r1-0528-qwen3-8b, gemini-2.5-flash, ..."
2,cynicism,"Meu avô era uma lenda, bicho. Vovô Lorival. Vo...",7,"[deepseek-r1-0528-qwen3-8b, gemini-2.5-flash, ..."
3,cynicism,"Não cara, não fique zangado porque eu já tive ...",7,"[deepseek-r1-0528-qwen3-8b, gemini-2.5-flash, ..."
4,cynicism,Não parece que antigamente passava mais devaga...,7,"[deepseek-r1-0528-qwen3-8b, gemini-2.5-flash, ..."
...,...,...,...,...
2306,wit,"Personagem 1: Opa primo, tudo bom? Só um salga...",4,"[gemma-3-gaia-pt-br-4b-it, llama-3-405b-instru..."
2307,wit,Aí o cara bota uma mensagem de Deus logo cedin...,4,"[gemini-2.5-flash, gemma-3-gaia-pt-br-4b-it, g..."
2308,wit,"Tem um sapo no interior e te chama, tu passa e...",4,"[gemma-3-gaia-pt-br-4b-it, llama-3-405b-instru..."
2309,wit,"Um fato histórico, deixa eu pensar. Um fato hi...",4,"[deepseek-r1-0528-qwen3-8b, gemma-3-gaia-pt-br..."
2310,wit,"A gente emagrece na força do ódio, a com raiva...",4,"[gemini-2.5-flash, gpt-4, granite-3-3-8b-instr..."