In [165]:
!pip install matplotlib vl-convert-python altair pandas operator altair numpy

Requirement already satisfied: matplotlib in ./new_venv/lib/python3.13/site-packages (3.10.6)
Requirement already satisfied: vl-convert-python in ./new_venv/lib/python3.13/site-packages (1.8.0)
Requirement already satisfied: altair in ./new_venv/lib/python3.13/site-packages (5.5.0)
Requirement already satisfied: pandas in ./new_venv/lib/python3.13/site-packages (2.2.3)
ERROR: Could not find a version that satisfies the requirement operator (from versions: none)
ERROR: No matching distribution found for operator

In [166]:
import altair as alt
import json
import pandas as pd
import numpy as np
import os

from statistics import mean

In [167]:
visus_folder_name = 'visualizations'
os.makedirs(visus_folder_name, exist_ok=True)
visus_path = os.path.join(os.getcwd(), visus_folder_name)

In [168]:
df_zero = pd.read_json('./evaluation/zero-shot/aggregate_metrics.json')
df_zero['setting'] = 'zero-shot'
df_zero

,gemma-3-gaia-pt-br-4b-it,mixtral-8x7b-instruct-v01,sabia-3.1,granite-3-3-8b-instruct,gemini-2.5-flash,gpt-4,gervasio-7b-portuguese-ptbr-decoder,llama-3-405b-instruct,deepseek-r1-0528-qwen3-8b,setting
punchlines,"{'dice_similarity': 0.486908473753753, 'hit_ra...","{'dice_similarity': 0.549397592450793, 'hit_ra...","{'dice_similarity': 0.6332983368475681, 'hit_r...","{'dice_similarity': 0.558850712853276, 'hit_ra...","{'dice_similarity': 0.682141771946278, 'hit_ra...","{'dice_similarity': 0.730168096279427, 'hit_ra...","{'dice_similarity': 0.012254901960784001, 'hit...","{'dice_similarity': 0.5946873289991981, 'hit_r...","{'dice_similarity': 0.19351009205241002, 'hit_...",zero-shot
comic_styles,"{'f1_score': {'fun': 0.867699642431466, 'humor...","{'f1_score': {'fun': 0.8688327316486161, 'humo...","{'f1_score': {'fun': 0.8653846153846151, 'humo...","{'f1_score': {'fun': 0.0, 'humor': 0.222222222...","{'f1_score': {'fun': 0.7873563218390801, 'humo...","{'f1_score': {'fun': 0.851511169513797, 'humor...","{'f1_score': {'fun': 0.877419354838709, 'humor...","{'f1_score': {'fun': 0.838874680306905, 'humor...","{'f1_score': {'fun': 0.867699642431466, 'humor...",zero-shot
texts_explanations,3.391579,3.364211,4.195789,3.642105,4.635789,4.282105,1.431579,3.972632,2.776842,zero-shot

In [169]:
df_few = pd.read_json('./evaluation/few-shot/aggregate_metrics.json')
df_few['setting'] = 'few-shot'
df_few

,gemma-3-gaia-pt-br-4b-it,sabia-3.1,granite-3-3-8b-instruct,gemini-2.5-flash,gpt-4,gervasio-7b-portuguese-ptbr-decoder,llama-3-405b-instruct,deepseek-r1-0528-qwen3-8b,setting
punchlines,"{'dice_similarity': 0.467893562334099, 'hit_ra...","{'dice_similarity': 0.614947308711401, 'hit_ra...","{'dice_similarity': 0.5437433490380701, 'hit_r...","{'dice_similarity': 0.717461596140731, 'hit_ra...","{'dice_similarity': 0.7284188116442041, 'hit_r...","{'dice_similarity': None, 'hit_rate_pre_treatm...","{'dice_similarity': 0.6537244663341091, 'hit_r...","{'dice_similarity': 0.46517622262209, 'hit_rat...",few-shot
comic_styles,"{'f1_score': {'fun': 0.867699642431466, 'humor...","{'f1_score': {'fun': 0.7482014388489201, 'humo...","{'f1_score': {'fun': 0.8158567774936061, 'humo...","{'f1_score': {'fun': 0.772393538913362, 'humor...","{'f1_score': {'fun': 0.8602941176470581, 'humo...",None,"{'f1_score': {'fun': 0.8490284005979071, 'humo...","{'f1_score': {'fun': 0.867699642431466, 'humor...",few-shot
texts_explanations,3.210526,4.090526,3.543158,4.307368,4.164211,1.576842,3.696842,2.117895,few-shot

In [170]:
df_all = pd.concat([df_zero, df_few])
df_all = df_all.reset_index().rename(columns={'index': 'task'})

df_long = df_all.melt(
    id_vars=['task', 'setting'], 
    var_name='model', 
    value_name='score'
)

df_long.head(3)

,task,setting,model,score
0,punchlines,zero-shot,gemma-3-gaia-pt-br-4b-it,"{'dice_similarity': 0.486908473753753, 'hit_ra..."
1,comic_styles,zero-shot,gemma-3-gaia-pt-br-4b-it,"{'f1_score': {'fun': 0.867699642431466, 'humor..."
2,texts_explanations,zero-shot,gemma-3-gaia-pt-br-4b-it,3.391579

In [171]:
model_short_names = {
    'gemma-3-gaia-pt-br-4b-it': 'Gemma 3 Gaia (4B)',
    'mixtral-8x7b-instruct-v01': 'Mixtral v01 (8×7B)',
    'sabia-3.1': 'Sabia 3.1',
    'granite-3-3-8b-instruct': 'Granite 3.3 (8B)',
    'gemini-2.5-flash': 'Gemini 2.5 Flash',
    'gpt-4': 'GPT-4',
    'llama-3-405b-instruct': 'LLaMA 3 (405B)',
    'deepseek-r1-0528-qwen3-8b': 'DeepSeek R1 (8B)',
    'gervasio-7b-portuguese-ptbr-decoder': 'Gervasio (7B)'
}

df_long['model'] = df_long['model'].apply(lambda model_name: model_short_names[model_name])
df_long.head(3)

,task,setting,model,score
0,punchlines,zero-shot,Gemma 3 Gaia (4B),"{'dice_similarity': 0.486908473753753, 'hit_ra..."
1,comic_styles,zero-shot,Gemma 3 Gaia (4B),"{'f1_score': {'fun': 0.867699642431466, 'humor..."
2,texts_explanations,zero-shot,Gemma 3 Gaia (4B),3.391579

In [172]:
def df_to_tabularx(df, caption="My Table", label="tab:mytable"):
    """
    Converte DataFrame em tabela LaTeX no formato tabularx, estilo conferência (com hlines).
    """
    # nomes das colunas em negrito
    headers = " & ".join([f"\\textbf{{{col}}}" for col in df.columns]) + " \\\\"

    # linhas da tabela
    rows = []
    for _, row in df.iterrows():
        row_str = " & ".join([str(val) for val in row]) + " \\\\"
        rows.append(row_str)

    # formato das colunas: primeira 'l', resto 'c'
    num_cols = df.shape[1]
    col_format = "l" + "c"*(num_cols-1)

    # monta a string LaTeX
    latex_str = (
        "\\begin{table}[ht]\n"
        "\\centering\n"
        f"\\begin{{tabularx}}{{\\columnwidth}}{{{col_format}}}\n"
        "\\hline\n"
        f"{headers}\n"
        "\\hline\n"
        + "\n".join(rows) + "\n"
        "\\hline\n"
        "\\end{tabularx}\n"
        f"\\caption{{{caption}}}\n"
        f"\\label{{{label}}}\n"
        "\\end{table}"
    )

    return latex_str

In [173]:
import os
import json
import pandas as pd

# Caminho da pasta principal
base_path = "evaluation"

# Cenários
cenarios = ["zero-shot", "few-shot"]

# Lista para armazenar os dados
dados = []

for cenario in cenarios:
    cenario_path = os.path.join(base_path, cenario)
    
    # Percorrer todos os arquivos JSON dentro da pasta do cenário
    for root, dirs, files in os.walk(cenario_path):
        for file in files:
            if file == "individual_metrics.json":
                file_path = os.path.join(root, file)
                
                # Abrir o JSON
                with open(file_path, "r") as f:
                    metrics = json.load(f)
                
                # metrics deve ser algo como { "modelo1": {...}, "modelo2": {...} }
                for modelo, valores in metrics.items():
                    # Adiciona cada resultado na lista
                    dados.append({
                        "cenario": cenario,
                        "modelo": modelo,
                        **valores  # desempacota as métricas do modelo
                    })

# Criar o DataFrame final
df_individuals = pd.DataFrame(dados)

df_individuals.head()

,cenario,modelo,punchlines,comic_styles,texts_explanations
0,zero-shot,gemma-3-gaia-pt-br-4b-it,[{'video_url': 'https://www.youtube.com/shorts...,[{'video_url': 'https://www.youtube.com/shorts...,[{'video_url': 'https://www.youtube.com/shorts...
1,zero-shot,mixtral-8x7b-instruct-v01,[{'video_url': 'https://www.youtube.com/shorts...,[{'video_url': 'https://www.youtube.com/shorts...,[{'video_url': 'https://www.youtube.com/shorts...
2,zero-shot,sabia-3.1,[{'video_url': 'https://www.youtube.com/shorts...,[{'video_url': 'https://www.youtube.com/shorts...,[{'video_url': 'https://www.youtube.com/shorts...
3,zero-shot,granite-3-3-8b-instruct,[{'video_url': 'https://www.youtube.com/shorts...,[{'video_url': 'https://www.youtube.com/shorts...,[{'video_url': 'https://www.youtube.com/shorts...
4,zero-shot,gemini-2.5-flash,[{'video_url': 'https://www.youtube.com/shorts...,[{'video_url': 'https://www.youtube.com/shorts...,[{'video_url': 'https://www.youtube.com/shorts...

### 1. Punchlines

In [174]:
# 1. Filtrar só punchlines
df_punch = df_long.query("task == 'punchlines'").copy()
df_punch

,task,setting,model,score
0,punchlines,zero-shot,Gemma 3 Gaia (4B),"{'dice_similarity': 0.486908473753753, 'hit_ra..."
3,punchlines,few-shot,Gemma 3 Gaia (4B),"{'dice_similarity': 0.467893562334099, 'hit_ra..."
6,punchlines,zero-shot,Mixtral v01 (8×7B),"{'dice_similarity': 0.549397592450793, 'hit_ra..."
9,punchlines,few-shot,Mixtral v01 (8×7B),NaN
12,punchlines,zero-shot,Sabia 3.1,"{'dice_similarity': 0.6332983368475681, 'hit_r..."
15,punchlines,few-shot,Sabia 3.1,"{'dice_similarity': 0.614947308711401, 'hit_ra..."
18,punchlines,zero-shot,Granite 3.3 (8B),"{'dice_similarity': 0.558850712853276, 'hit_ra..."
21,punchlines,few-shot,Granite 3.3 (8B),"{'dice_similarity': 0.5437433490380701, 'hit_r..."
24,punchlines,zero-shot,Gemini 2.5 Flash,"{'dice_similarity': 0.682141771946278, 'hit_ra..."
27,punchlines,few-shot,Gemini 2.5 Flash,"{'dice_similarity': 0.717461596140731, 'hit_ra..."
30,punchlines,zero-shot,GPT-4,"{'dice_similarity': 0.730168096279427, 'hit_ra..."
33,punchlines,few-shot,GPT-4,"{'dice_similarity': 0.7284188116442041, 'hit_r..."
36,punchlines,zero-shot,Gervasio (7B),"{'dice_similarity': 0.012254901960784001, 'hit..."
39,punchlines,few-shot,Gervasio (7B),"{'dice_similarity': None, 'hit_rate_pre_treatm..."
42,punchlines,zero-shot,LLaMA 3 (405B),"{'dice_similarity': 0.5946873289991981, 'hit_r..."
45,punchlines,few-shot,LLaMA 3 (405B),"{'dice_similarity': 0.6537244663341091, 'hit_r..."
48,punchlines,zero-shot,DeepSeek R1 (8B),"{'dice_similarity': 0.19351009205241002, 'hit_..."
51,punchlines,few-shot,DeepSeek R1 (8B),"{'dice_similarity': 0.46517622262209, 'hit_rat..."

In [175]:
valid_models = [
    model for model in df_punch['model'].unique()
    if all(
        isinstance(v, dict) and v.get('dice_similarity') is not None
        for v in df_punch.loc[df_punch['model'] == model, 'score']
    )
]

df_punch_plot = df_punch[df_punch['model'].isin(valid_models)]

In [176]:
df_plot = df_punch_plot.copy()
df_plot['dice_similarity'] = df_plot['score'].apply(lambda x: x['dice_similarity'] if isinstance(x, dict) else None)
dice_order = df_plot[df_plot['setting'] == 'zero-shot'].sort_values('dice_similarity', ascending=False)['model'].tolist()
df_plot['setting'] = pd.Categorical(df_plot['setting'], categories=['zero-shot', 'few-shot'], ordered=True)

chart_dice = alt.Chart(df_plot).mark_bar(size=20).encode(
    y=alt.Y('model:N', sort=dice_order, title=' ', axis=alt.Axis(grid=False)),
    x=alt.X('dice_similarity:Q', title='Média da Similaridade de Dice', axis=alt.Axis(grid=False, titleY=30)),
    color=alt.Color('setting:N', title='Configuração'),
    yOffset=alt.YOffset('setting:N')
).properties(
    width=500,
    height=400,
    title='Comparação Zero-shot vs Few-shot — Identificação de Punchlines'
)

visus_path = visus_folder_name
os.makedirs(visus_path, exist_ok=True)
chart_dice.save(os.path.join(visus_path, "similaridade_dice_vertical_barras.png"), scale_factor=3.0)
chart_dice.show()

alt.Chart(...)

In [177]:
print(df_plot.to_latex(index=False, float_format="%.2f".__mod__))

\begin{tabular}{llllr}
\toprule
task & setting & model & score & dice_similarity \\
\midrule
punchlines & zero-shot & Gemma 3 Gaia (4B) & {'dice_similarity': 0.486908473753753, 'hit_rate_pre_treatment': 0.0, 'hit_rate': 0.9936842105263151} & 0.49 \\
punchlines & few-shot & Gemma 3 Gaia (4B) & {'dice_similarity': 0.467893562334099, 'hit_rate_pre_treatment': 0.0, 'hit_rate': 0.713684210526315} & 0.47 \\
punchlines & zero-shot & Sabia 3.1 & {'dice_similarity': 0.6332983368475681, 'hit_rate_pre_treatment': 0.9852631578947361, 'hit_rate': 0.9957894736842101} & 0.63 \\
punchlines & few-shot & Sabia 3.1 & {'dice_similarity': 0.614947308711401, 'hit_rate_pre_treatment': 0.949473684210526, 'hit_rate': 0.953684210526315} & 0.61 \\
punchlines & zero-shot & Granite 3.3 (8B) & {'dice_similarity': 0.558850712853276, 'hit_rate_pre_treatment': 0.842105263157894, 'hit_rate': 0.945263157894736} & 0.56 \\
punchlines & few-shot & Granite 3.3 (8B) & {'dice_similarity': 0.5437433490380701, 'hit_rate_pre_treatment': 0.0063157894736840005, 'hit_rate': 0.050526315789473} & 0.54 \\
punchlines & zero-shot & Gemini 2.5 Flash & {'dice_similarity': 0.682141771946278, 'hit_rate_pre_treatment': 0.9936842105263151, 'hit_rate': 0.9936842105263151} & 0.68 \\
punchlines & few-shot & Gemini 2.5 Flash & {'dice_similarity': 0.717461596140731, 'hit_rate_pre_treatment': 0.9915789473684211, 'hit_rate': 0.9957894736842101} & 0.72 \\
punchlines & zero-shot & GPT-4 & {'dice_similarity': 0.730168096279427, 'hit_rate_pre_treatment': 0.9978947368421051, 'hit_rate': 0.9978947368421051} & 0.73 \\
punchlines & few-shot & GPT-4 & {'dice_similarity': 0.7284188116442041, 'hit_rate_pre_treatment': 0.9978947368421051, 'hit_rate': 0.9978947368421051} & 0.73 \\
punchlines & zero-shot & LLaMA 3 (405B) & {'dice_similarity': 0.5946873289991981, 'hit_rate_pre_treatment': 0.9831578947368421, 'hit_rate': 0.9936842105263151} & 0.59 \\
punchlines & few-shot & LLaMA 3 (405B) & {'dice_similarity': 0.6537244663341091, 'hit_rate_pre_treatment': 0.9810526315789471, 'hit_rate': 0.9894736842105261} & 0.65 \\
punchlines & zero-shot & DeepSeek R1 (8B) & {'dice_similarity': 0.19351009205241002, 'hit_rate_pre_treatment': 0.0, 'hit_rate': 0.157894736842105} & 0.19 \\
punchlines & few-shot & DeepSeek R1 (8B) & {'dice_similarity': 0.46517622262209, 'hit_rate_pre_treatment': 0.0, 'hit_rate': 0.206315789473684} & 0.47 \\
\bottomrule
\end{tabular}

In [178]:
from scipy import stats

def mean_ci(data, confidence=0.95):
    data = np.array(data)
    mean = np.mean(data)
    if len(data) > 1:
        sem = stats.sem(data)  # erro padrão da média
        h = sem * stats.t.ppf((1 + confidence) / 2., len(data)-1)
        return mean, mean-h, mean+h
    else:
        return mean, mean, mean  # se só houver 1 valor

# Agrupar por modelo e configuração
agg_data = []
for (model, setting), group in df_plot.groupby(['model', 'setting']):
    scores = group['dice_similarity'].dropna()
    mean, lower, upper = mean_ci(scores)
    agg_data.append({
        'model': model,
        'setting': setting,
        'mean_dice': mean,
        'ci_lower': lower,
        'ci_upper': upper
    })

df_table = pd.DataFrame(agg_data)

# Opcional: ordenar por média zero-shot
zero_shot_order = df_table[df_table['setting'] == 'zero-shot'].sort_values('mean_dice', ascending=False)['model']
df_table['model'] = pd.Categorical(df_table['model'], categories=zero_shot_order, ordered=True)

# Mostrar tabela
df_table.sort_values(['setting', 'model'], ascending=[True, True])

/tmp/ipykernel_6251/3056727324.py:15: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for (model, setting), group in df_plot.groupby(['model', 'setting']):

                model    setting  mean_dice  ci_lower  ci_upper
3               GPT-4   few-shot   0.728419  0.728419  0.728419
5    Gemini 2.5 Flash   few-shot   0.717462  0.717462  0.717462
13          Sabia 3.1   few-shot   0.614947  0.614947  0.614947
11     LLaMA 3 (405B)   few-shot   0.653724  0.653724  0.653724
9    Granite 3.3 (8B)   few-shot   0.543743  0.543743  0.543743
7   Gemma 3 Gaia (4B)   few-shot   0.467894  0.467894  0.467894
1    DeepSeek R1 (8B)   few-shot   0.465176  0.465176  0.465176
2               GPT-4  zero-shot   0.730168  0.730168  0.730168
4    Gemini 2.5 Flash  zero-shot   0.682142  0.682142  0.682142
12          Sabia 3.1  zero-shot   0.633298  0.633298  0.633298
10     LLaMA 3 (405B)  zero-shot   0.594687  0.594687  0.594687
8    Granite 3.3 (8B)  zero-shot   0.558851  0.558851  0.558851
6   Gemma 3 Gaia (4B)  zero-shot   0.486908  0.486908  0.486908
0    DeepSeek R1 (8B)  zero-shot   0.193510  0.193510  0.193510

In [179]:
latex_table = df_table.to_latex(index=False, float_format="%.2f".__mod__)
print(latex_table)

\begin{tabular}{llrrr}
\toprule
model & setting & mean_dice & ci_lower & ci_upper \\
\midrule
DeepSeek R1 (8B) & zero-shot & 0.19 & 0.19 & 0.19 \\
DeepSeek R1 (8B) & few-shot & 0.47 & 0.47 & 0.47 \\
GPT-4 & zero-shot & 0.73 & 0.73 & 0.73 \\
GPT-4 & few-shot & 0.73 & 0.73 & 0.73 \\
Gemini 2.5 Flash & zero-shot & 0.68 & 0.68 & 0.68 \\
Gemini 2.5 Flash & few-shot & 0.72 & 0.72 & 0.72 \\
Gemma 3 Gaia (4B) & zero-shot & 0.49 & 0.49 & 0.49 \\
Gemma 3 Gaia (4B) & few-shot & 0.47 & 0.47 & 0.47 \\
Granite 3.3 (8B) & zero-shot & 0.56 & 0.56 & 0.56 \\
Granite 3.3 (8B) & few-shot & 0.54 & 0.54 & 0.54 \\
LLaMA 3 (405B) & zero-shot & 0.59 & 0.59 & 0.59 \\
LLaMA 3 (405B) & few-shot & 0.65 & 0.65 & 0.65 \\
Sabia 3.1 & zero-shot & 0.63 & 0.63 & 0.63 \\
Sabia 3.1 & few-shot & 0.61 & 0.61 & 0.61 \\
\bottomrule
\end{tabular}

In [180]:
def to_list(x):
    if isinstance(x, str):
        return json.loads(x)
    elif isinstance(x, list):
        return x
    else:
        return []  # caso seja None ou outro tipo inesperado

df_individuals['punchlines'] = df_individuals['punchlines'].apply(to_list)
df_exploded = df_individuals.explode('punchlines')
df_exploded = df_exploded.rename(columns={'punchlines': 'punchlines'})
df_exploded = df_exploded[['cenario', 'modelo', 'punchlines']]

df_exploded['dice_sim'] = df_exploded['punchlines'].apply(lambda x: x['dice_similarity'])
df_exploded

,cenario,modelo,punchlines,dice_sim
0,zero-shot,gemma-3-gaia-pt-br-4b-it,{'video_url': 'https://www.youtube.com/shorts/...,0.243902
0,zero-shot,gemma-3-gaia-pt-br-4b-it,{'video_url': 'https://www.youtube.com/shorts/...,0.297872
0,zero-shot,gemma-3-gaia-pt-br-4b-it,{'video_url': 'https://www.youtube.com/shorts/...,0.626866
0,zero-shot,gemma-3-gaia-pt-br-4b-it,{'video_url': 'https://www.youtube.com/shorts/...,0.193548
0,zero-shot,gemma-3-gaia-pt-br-4b-it,{'video_url': 'https://www.youtube.com/shorts/...,0.636364
...,...,...,...,...
16,few-shot,deepseek-r1-0528-qwen3-8b,{'video_url': 'https://www.youtube.com/shorts/...,NaN
16,few-shot,deepseek-r1-0528-qwen3-8b,{'video_url': 'https://www.youtube.com/shorts/...,NaN
16,few-shot,deepseek-r1-0528-qwen3-8b,{'video_url': 'https://www.youtube.com/shorts/...,NaN
16,few-shot,deepseek-r1-0528-qwen3-8b,{'video_url': 'https://www.youtube.com/shorts/...,NaN
16,few-shot,deepseek-r1-0528-qwen3-8b,{'video_url': 'https://www.youtube.com/shorts/...,NaN

In [181]:
import scipy.stats as st

df_exploded['dice_sim'] = pd.to_numeric(df_exploded['dice_sim'], errors='coerce')

# Remove linhas com NaN
df_exploded = df_exploded.dropna(subset=['dice_sim'])

# Função de média e IC
def mean_confidence_interval(data, confidence=0.95):
    n = len(data)
    mean = data.mean()
    if n < 2:
        return mean, mean, mean
    se = st.sem(data)  # erro padrão da média
    h = se * st.t.ppf((1 + confidence) / 2., n-1)
    return mean, mean - h, mean + h

# Agrupa e calcula
summary_list = []
for (cenario, modelo), group in df_exploded.groupby(['cenario', 'modelo']):
    mean, ci_lower, ci_upper = mean_confidence_interval(group['dice_sim'])
    summary_list.append({
        'cenario': cenario,
        'modelo': modelo,
        'mean': mean,
        'ci_lower': ci_lower,
        'ci_upper': ci_upper
    })

summary_df = pd.DataFrame(summary_list)
summary_df

,cenario,modelo,mean,ci_lower,ci_upper
0,few-shot,deepseek-r1-0528-qwen3-8b,0.465176,0.410056,0.520296
1,few-shot,gemini-2.5-flash,0.717462,0.697647,0.737276
2,few-shot,gemma-3-gaia-pt-br-4b-it,0.467894,0.440513,0.495274
3,few-shot,gpt-4,0.728419,0.711021,0.745816
4,few-shot,granite-3-3-8b-instruct,0.543743,0.415119,0.672368
5,few-shot,llama-3-405b-instruct,0.653724,0.631476,0.675973
6,few-shot,sabia-3.1,0.614947,0.593686,0.636208
7,zero-shot,deepseek-r1-0528-qwen3-8b,0.193510,0.134973,0.252047
8,zero-shot,gemini-2.5-flash,0.682142,0.660979,0.703304
9,zero-shot,gemma-3-gaia-pt-br-4b-it,0.486908,0.464551,0.509266
10,zero-shot,gervasio-7b-portuguese-ptbr-decoder,0.012255,-0.007668,0.032177
11,zero-shot,gpt-4,0.730168,0.713483,0.746853
12,zero-shot,granite-3-3-8b-instruct,0.558851,0.537932,0.579770
13,zero-shot,llama-3-405b-instruct,0.594687,0.571058,0.618316
14,zero-shot,mixtral-8x7b-instruct-v01,0.549398,0.528071,0.570724
15,zero-shot,sabia-3.1,0.633298,0.614903,0.651694

In [182]:
summary_df_latex = summary_df.to_latex(index=False, float_format="%.2f".__mod__)
print(summary_df_latex)

\begin{tabular}{llrrr}
\toprule
cenario & modelo & mean & ci_lower & ci_upper \\
\midrule
few-shot & deepseek-r1-0528-qwen3-8b & 0.47 & 0.41 & 0.52 \\
few-shot & gemini-2.5-flash & 0.72 & 0.70 & 0.74 \\
few-shot & gemma-3-gaia-pt-br-4b-it & 0.47 & 0.44 & 0.50 \\
few-shot & gpt-4 & 0.73 & 0.71 & 0.75 \\
few-shot & granite-3-3-8b-instruct & 0.54 & 0.42 & 0.67 \\
few-shot & llama-3-405b-instruct & 0.65 & 0.63 & 0.68 \\
few-shot & sabia-3.1 & 0.61 & 0.59 & 0.64 \\
zero-shot & deepseek-r1-0528-qwen3-8b & 0.19 & 0.13 & 0.25 \\
zero-shot & gemini-2.5-flash & 0.68 & 0.66 & 0.70 \\
zero-shot & gemma-3-gaia-pt-br-4b-it & 0.49 & 0.46 & 0.51 \\
zero-shot & gervasio-7b-portuguese-ptbr-decoder & 0.01 & -0.01 & 0.03 \\
zero-shot & gpt-4 & 0.73 & 0.71 & 0.75 \\
zero-shot & granite-3-3-8b-instruct & 0.56 & 0.54 & 0.58 \\
zero-shot & llama-3-405b-instruct & 0.59 & 0.57 & 0.62 \\
zero-shot & mixtral-8x7b-instruct-v01 & 0.55 & 0.53 & 0.57 \\
zero-shot & sabia-3.1 & 0.63 & 0.61 & 0.65 \\
\bottomrule
\end{tabular}

### 2. Text Explanation

In [183]:
df_texts = df_long.query("task == 'texts_explanations'").copy()
df_texts_plot = df_texts[df_texts['model'].isin(valid_models)]
df_texts_plot

                  task    setting              model     score
2   texts_explanations  zero-shot  Gemma 3 Gaia (4B)  3.391579
5   texts_explanations   few-shot  Gemma 3 Gaia (4B)  3.210526
14  texts_explanations  zero-shot          Sabia 3.1  4.195789
17  texts_explanations   few-shot          Sabia 3.1  4.090526
20  texts_explanations  zero-shot   Granite 3.3 (8B)  3.642105
23  texts_explanations   few-shot   Granite 3.3 (8B)  3.543158
26  texts_explanations  zero-shot   Gemini 2.5 Flash  4.635789
29  texts_explanations   few-shot   Gemini 2.5 Flash  4.307368
32  texts_explanations  zero-shot              GPT-4  4.282105
35  texts_explanations   few-shot              GPT-4  4.164211
44  texts_explanations  zero-shot     LLaMA 3 (405B)  3.972632
47  texts_explanations   few-shot     LLaMA 3 (405B)  3.696842
50  texts_explanations  zero-shot   DeepSeek R1 (8B)  2.776842
53  texts_explanations   few-shot   DeepSeek R1 (8B)  2.117895

In [184]:
df_expl_plot = df_texts_plot.copy()
df_expl_plot['metric'] = df_expl_plot['score']
zero_shot_order = df_expl_plot[df_expl_plot['setting'] == 'zero-shot'].sort_values('metric', ascending=False)['model'].tolist()
df_expl_plot['setting'] = pd.Categorical(df_expl_plot['setting'], categories=['zero-shot', 'few-shot'], ordered=True)

chart_texts = alt.Chart(df_expl_plot).mark_bar(size=20).encode(
    y=alt.Y('model:N', sort=zero_shot_order, title=' ', axis=alt.Axis(grid=False)),
    x=alt.X(
        'metric:Q',
        title='Média do Nível de Concordância - Modelo Juiz',
        axis=alt.Axis(grid=False, titleY=30),
        scale=alt.Scale(domain=[1, 5], clamp = True) 
    ),
    color=alt.Color('setting:N', title='Configuração'),
    yOffset=alt.YOffset('setting:N')
).properties(
    width=500,
    height=400,
    title='Comparação Zero-shot vs Few-shot — Explicações dos Textos'
)

visus_path = visus_folder_name
os.makedirs(visus_path, exist_ok=True)
chart_texts.save(os.path.join(visus_path, "texts_explanations_vertical_barras.png"), scale_factor=3.0)
chart_texts.show()

alt.Chart(...)

In [185]:
files = {
    "zero-shot": "evaluation/zero-shot/texts_explanations_evaluation_results.json",
    "few-shot": "evaluation/few-shot/texts_explanations_evaluation_results.json"
}

records = []

for setting, filepath in files.items():
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    for model, videos in data.items():
        for video_url, content in videos.items():
            nivel = int(content["judge_model_results"]["nivel_concordancia"])
            records.append({
                "model": model,
                "video_url": video_url,
                "nivel_concordancia": nivel,
                "setting": setting
            })

df = pd.DataFrame(records)
df.head(3)

,model,video_url,nivel_concordancia,setting
0,gemini-2.5-flash,https://www.youtube.com/shorts/Xcve3ifSxWg?fea...,4,zero-shot
1,gemini-2.5-flash,https://www.youtube.com/shorts/QV80EKixLYc?fea...,5,zero-shot
2,gemini-2.5-flash,https://www.youtube.com/shorts/yn3-Kmp7hjM?fea...,5,zero-shot

In [186]:
df_counts = (
    df.groupby(["model", "setting", "nivel_concordancia"])
    .size()
    .reset_index(name="count")
)

# proporção dentro de cada modelo+setting
df_counts["proportion"] = (
    df_counts["count"] / 
    df_counts.groupby(["model", "setting"])["count"].transform("sum")
)

df_counts = df_counts[~df_counts['model'].str.contains('mixtral|gervasio', case=False, na=False)]

df_counts

,model,setting,nivel_concordancia,count,proportion
0,deepseek-r1-0528-qwen3-8b,few-shot,1,190,0.400000
1,deepseek-r1-0528-qwen3-8b,few-shot,2,169,0.355789
2,deepseek-r1-0528-qwen3-8b,few-shot,3,24,0.050526
3,deepseek-r1-0528-qwen3-8b,few-shot,4,54,0.113684
4,deepseek-r1-0528-qwen3-8b,few-shot,5,38,0.080000
...,...,...,...,...,...
80,sabia-3.1,zero-shot,1,16,0.033684
81,sabia-3.1,zero-shot,2,65,0.136842
82,sabia-3.1,zero-shot,3,14,0.029474
83,sabia-3.1,zero-shot,4,95,0.200000
84,sabia-3.1,zero-shot,5,285,0.600000

In [187]:
heatmap_layer = alt.layer(
    alt.Chart(df_counts).mark_rect().encode(
        x=alt.X("nivel_concordancia:N", title="Agreement Level", axis=alt.Axis(labelAngle=0)),
        y=alt.Y("model:N", title="Model"),
        color=alt.Color(
            "proportion:Q",
            title="Proportion",
            scale=alt.Scale(scheme="blues", domain=[0, 1]),
            legend=alt.Legend(format=".2f", orient="right", gradientLength=200)
        ),
        tooltip=["model", "setting", "nivel_concordancia", "proportion"]
    ).properties(
        width=180,
        height=250
    ),
    alt.Chart(df_counts).mark_text(color='black', fontSize=11.5).encode(
        x="nivel_concordancia:N",
        y="model:N",
        text=alt.Text("proportion:Q", format=".2f")
    )
)

'''heatmap_with_text = heatmap_layer.facet(
    column=alt.Column("setting:N", title="Prompting Setting")
).properties(
    title={
        "text": "Proportion of Ratings by Agreement Level",
        "subtitle": (
            "Rated by the judge model (o3-mini) against reference answers in the Humor Reasoning task."
        )
    }
)'''

heatmap_with_text = heatmap_layer.facet(
    column=alt.Column("setting:N", title="")
).properties(
    title={
        "text": " "
    }
)

heatmap_with_text.save(os.path.join(visus_path, "expl_1.png"), scale_factor=3.0)
heatmap_with_text.show()

alt.FacetChart(...)

In [188]:
print(df_expl_plot.to_latex(index=False, float_format="%.2f".__mod__))

\begin{tabular}{lllll}
\toprule
task & setting & model & score & metric \\
\midrule
texts_explanations & zero-shot & Gemma 3 Gaia (4B) & 3.39 & 3.39 \\
texts_explanations & few-shot & Gemma 3 Gaia (4B) & 3.21 & 3.21 \\
texts_explanations & zero-shot & Sabia 3.1 & 4.20 & 4.20 \\
texts_explanations & few-shot & Sabia 3.1 & 4.09 & 4.09 \\
texts_explanations & zero-shot & Granite 3.3 (8B) & 3.64 & 3.64 \\
texts_explanations & few-shot & Granite 3.3 (8B) & 3.54 & 3.54 \\
texts_explanations & zero-shot & Gemini 2.5 Flash & 4.64 & 4.64 \\
texts_explanations & few-shot & Gemini 2.5 Flash & 4.31 & 4.31 \\
texts_explanations & zero-shot & GPT-4 & 4.28 & 4.28 \\
texts_explanations & few-shot & GPT-4 & 4.16 & 4.16 \\
texts_explanations & zero-shot & LLaMA 3 (405B) & 3.97 & 3.97 \\
texts_explanations & few-shot & LLaMA 3 (405B) & 3.70 & 3.70 \\
texts_explanations & zero-shot & DeepSeek R1 (8B) & 2.78 & 2.78 \\
texts_explanations & few-shot & DeepSeek R1 (8B) & 2.12 & 2.12 \\
\bottomrule
\end{tabular}

### 3. Comic Styles

In [189]:
df_comic = df_long.query("task == 'comic_styles'").copy()
df_comic.head(3)

,task,setting,model,score
1,comic_styles,zero-shot,Gemma 3 Gaia (4B),"{'f1_score': {'fun': 0.867699642431466, 'humor..."
4,comic_styles,few-shot,Gemma 3 Gaia (4B),"{'f1_score': {'fun': 0.867699642431466, 'humor..."
7,comic_styles,zero-shot,Mixtral v01 (8×7B),"{'f1_score': {'fun': 0.8688327316486161, 'humo..."

In [190]:
df_comic_plot = df_comic[
    df_comic['score'].apply(lambda x: isinstance(x, dict) and 'f1_macro' in x)
].copy()

df_comic_plot['score'] = df_comic_plot['score'].apply(lambda x: x['f1_macro'])

model_order = (
    df_comic_plot[df_comic_plot['setting'] == 'zero-shot']
    .sort_values('score', ascending=False)['model']
    .tolist()
)

df_comic_plot['setting'] = pd.Categorical(
    df_comic_plot['setting'], categories=['zero-shot', 'few-shot'], ordered=True
)

chart_comic = alt.Chart(df_comic_plot).mark_bar(size=20).encode(
    y=alt.Y('model:N', sort=model_order, title='', axis=alt.Axis(grid=False)),
    x=alt.X(
        'score:Q',
        title='F1 Macro (Estilos Cômicos)',
        axis=alt.Axis(grid=False, titleY=30),
        scale=alt.Scale(domain=[0, 1], clamp=True)
    ),
    color=alt.Color('setting:N', title='Configuração'),
    yOffset=alt.YOffset('setting:N')
).properties(
    width=500,
    height=400,
    title='Comparação Zero-shot vs Few-shot — Estilos Cômicos (F1 Macro)'
)

visus_path = visus_folder_name
os.makedirs(visus_path, exist_ok=True)
chart_comic.save(os.path.join(visus_path, "comic_styles_f1macro.png"), scale_factor=3.0)
chart_comic.show()

alt.Chart(...)

In [191]:
print(df_comic_plot.to_latex(index=False, float_format="%.2f".__mod__))

\begin{tabular}{lllr}
\toprule
task & setting & model & score \\
\midrule
comic_styles & zero-shot & Gemma 3 Gaia (4B) & 0.12 \\
comic_styles & few-shot & Gemma 3 Gaia (4B) & 0.12 \\
comic_styles & zero-shot & Mixtral v01 (8×7B) & 0.14 \\
comic_styles & zero-shot & Sabia 3.1 & 0.20 \\
comic_styles & few-shot & Sabia 3.1 & 0.25 \\
comic_styles & zero-shot & Granite 3.3 (8B) & 0.18 \\
comic_styles & few-shot & Granite 3.3 (8B) & 0.21 \\
comic_styles & zero-shot & Gemini 2.5 Flash & 0.25 \\
comic_styles & few-shot & Gemini 2.5 Flash & 0.25 \\
comic_styles & zero-shot & GPT-4 & 0.25 \\
comic_styles & few-shot & GPT-4 & 0.24 \\
comic_styles & zero-shot & Gervasio (7B) & 0.13 \\
comic_styles & zero-shot & LLaMA 3 (405B) & 0.24 \\
comic_styles & few-shot & LLaMA 3 (405B) & 0.22 \\
comic_styles & zero-shot & DeepSeek R1 (8B) & 0.12 \\
comic_styles & few-shot & DeepSeek R1 (8B) & 0.12 \\
\bottomrule
\end{tabular}

In [192]:
valid_models = [
    model for model in df_comic['model'].unique()
    if all(
        isinstance(v, dict) and 'f1_score' in v and all(pd.notna(score) for score in v['f1_score'].values())
        for v in df_comic.loc[df_comic['model'] == model, 'score']
    )
]

df_comic_plot = df_comic[df_comic['model'].isin(valid_models)].copy()

rows = []
for _, row in df_comic_plot.iterrows():
    f1_scores = row['score']['f1_score']
    for style, value in f1_scores.items():
        if pd.notna(value):
            rows.append({
                'model': row['model'],
                'setting': row['setting'],
                'style': style,
                'score': value
            })

df_comic_long = pd.DataFrame(rows)

model_order = (
    df_comic_long[df_comic_long['setting'] == 'zero-shot']
    .groupby('model')['score'].mean()
    .sort_values(ascending=False)
    .index.tolist()
)

df_comic_long['setting'] = pd.Categorical(df_comic_long['setting'], categories=['zero-shot', 'few-shot'], ordered=True)

chart_comic = alt.Chart(df_comic_long).mark_bar(size=20).encode(
    y=alt.Y('model:N', sort=model_order, title=' ', axis=alt.Axis(grid=False)),
    x=alt.X('score:Q', title='F1 Score', axis=alt.Axis(grid=False, titleY=30), scale=alt.Scale(domain=[0,1], clamp=True)),
    color=alt.Color('setting:N', title='Configuração'),
    yOffset=alt.YOffset('setting:N'),
    column=alt.Column('style:N', title=' ')  # cada estilo em uma coluna
).properties(
    width=150,
    height=400,
    title='Comparação Zero-shot vs Few-shot — Estilos Cômicos (F1 Score)'
)

visus_path = visus_folder_name
os.makedirs(visus_path, exist_ok=True)
chart_comic.save(os.path.join(visus_path, "comic_styles_vertical_barras.png"), scale_factor=3.0)
chart_comic.show()

alt.Chart(...)